# Generated by Django 4.1.1 on 2022-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=100)),
                ('descripccion', models.CharField(max_length=1000)),
            ],
        ),
    ]
